package com.chawuzhi.admin.mapper;

import java.util.List;

import org.apache.ibatis.annotations.Param;

import com.chawuzhi.admin.pojo.TbOrderItem;
import com.chawuzhi.admin.pojo.TbOrderItemExample;

public interface TbOrderItemMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_order_item
     *
     * @mbggenerated Wed Apr 25 11:12:29 CST 2018
     */
    int countByExample(TbOrderItemExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_order_item
     *
     * @mbggenerated Wed Apr 25 11:12:29 CST 2018
     */
    int deleteByExample(TbOrderItemExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_order_item
     *
     * @mbggenerated Wed Apr 25 11:12:29 CST 2018
     */
    int insert(TbOrderItem record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_order_item
     *
     * @mbggenerated Wed Apr 25 11:12:29 CST 2018
     */
    int insertSelective(TbOrderItem record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_order_item
     *
     * @mbggenerated Wed Apr 25 11:12:29 CST 2018
     */
    List<TbOrderItem> selectByExample(TbOrderItemExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_order_item
     *
     * @mbggenerated Wed Apr 25 11:12:29 CST 2018
     */
    int updateByExampleSelective(@Param("record") TbOrderItem record, @Param("example") TbOrderItemExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_order_item
     *
     * @mbggenerated Wed Apr 25 11:12:29 CST 2018
     */
    int updateByExample(@Param("record") TbOrderItem record, @Param("example") TbOrderItemExample example);
}